#!/bin/bash
echo "$test"
if [ "$#" -eq 1 ]; then
    windowsPath="\\\\wsl.localhost\\Ubuntu-20.04$(pwd)\\$1"
    windowsPath=$(echo "$windowsPath" | tr '/' '\\')
    powershell.exe "ii $windowsPath"
fi
